apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: coderhouse-api-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: coderhouse-api
    kind: Deployment
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50 # Scale if CPU usage is above 50%
